{{- if and .Values.apiKey.value (not .Values.apiKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bedrock-gateway.fullname" . }}-apikey
  labels:
    {{- include "bedrock-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.apiKey.value | quote }}
{{- end }}
