//! Non-streaming Bedrock Converse output → OpenAI **Responses API** mapping.
//!
//! The Responses analogue of [`crate::bedrock::response`] (the chat mapper). It
//! turns a Bedrock Converse output (the full response object as a
//! [`serde_json::Value`]) into a [`ResponsesResponse`]. Pure and synchronous —
//! it never calls Bedrock — so it is fully testable offline with synthetic
//! Converse output JSON.
//!
//! ## Differences from the chat mapper (deliberate)
//!
//! - **Reasoning is a structured output item, NOT `<think>` inline.** When the
//!   Bedrock output carries a `reasoningContent` block, this emits a
//!   [`ResponseOutputItem::Reasoning`] FIRST, carrying the reasoning text in a
//!   `summary` array. The chat path's `<think>...</think>` rendering is
//!   intentionally NOT used here.
//! - **Output items in spec order:** reasoning (if any) → message (text) and/or
//!   function_call items (on `tool_use`).
//! - **Responses usage field names:** `input_tokens` / `output_tokens` /
//!   `total_tokens`, with `input_tokens_details.cached_tokens` and
//!   `output_tokens_details.reasoning_tokens`.
//!
//! ## Shared accounting
//!
//! Token usage is rebuilt via the shared [`compute_token_usage`] helper (the
//! single source of truth, also used by the chat mapper and the streaming usage
//! chunk) — no separate token formula lives here. Reasoning tokens reuse
//! [`estimate_reasoning_tokens`] on the concatenated reasoning text.
//!
//! ## De-hardcoding
//!
//! No model-id literals. The `model` string flows through verbatim from the
//! caller into the response `model` field.

use std::time::{SystemTime, UNIX_EPOCH};

use std::collections::HashMap;

use serde_json::{json, Value};

use crate::bedrock::responses_translate::{
    encode_reasoning_envelope, ResponsesToolKind, ResponsesToolRegistry,
};
use crate::bedrock::tokens::{compute_token_usage, estimate_reasoning_tokens};
use crate::error::AppError;
use crate::openai::responses_schema::{
    InputTokensDetails, OutputContentPart, OutputTokensDetails, ResponseOutputItem,
    ResponsesRequest, ResponsesResponse, ResponsesUsage,
};

/// Map a Bedrock Converse output to an OpenAI [`ResponsesResponse`].
///
/// `output` is the full Bedrock Converse response object (carrying
/// `output.message.content`, `usage`, and `stopReason`). `req` is the original
/// Responses request, used to echo back the relevant params (model echoes the
/// resolved `model` argument, not `req.model`). `model` is echoed verbatim into
/// the response; `response_id` becomes the response `id` (a `resp_`-prefixed
/// value generated by the caller).
///
/// Output items are built in spec order:
/// 1. a [`ResponseOutputItem::Reasoning`] FIRST when `reasoningContent` is
///    present (the reasoning text carried in `summary`),
/// 2. then, on a `tool_use` stop reason, one
///    [`ResponseOutputItem::FunctionCall`] per Bedrock `toolUse` block;
///    otherwise a single [`ResponseOutputItem::Message`] coalescing all text
///    blocks into ONE `output_text` content part.
///
/// `status` is `"completed"` unless the stop reason maps to an incomplete state
/// (`max_tokens` → `incomplete_details.reason = "max_output_tokens"`,
/// `content_filtered` → `"content_filter"`).
///
/// # Errors
///
/// Returns [`AppError::Internal`] if the output is missing the
/// `output.message.content` array (a malformed upstream response) or a
/// `toolUse` block's input cannot be serialized.
pub fn from_converse_output_to_responses(
    output: &Value,
    req: &ResponsesRequest,
    model: &str,
    response_id: &str,
) -> Result<ResponsesResponse, AppError> {
    from_converse_output_to_responses_with_tools(
        output,
        req,
        model,
        response_id,
        &ResponsesToolRegistry::default(),
    )
}

pub(crate) fn from_converse_output_to_responses_with_tools(
    output: &Value,
    req: &ResponsesRequest,
    model: &str,
    response_id: &str,
    tool_registry: &ResponsesToolRegistry,
) -> Result<ResponsesResponse, AppError> {
    let content = output
        .get("output")
        .and_then(|o| o.get("message"))
        .and_then(|m| m.get("content"))
        .and_then(Value::as_array)
        .ok_or_else(|| {
            AppError::Internal(
                "bedrock converse output missing output.message.content array".to_string(),
            )
        })?;

    let stop_reason = output.get("stopReason").and_then(Value::as_str);

    let usage_value = output.get("usage");
    let counts = compute_token_usage(
        usage_field(usage_value, "inputTokens"),
        usage_field(usage_value, "outputTokens"),
        usage_field(usage_value, "cacheReadInputTokens"),
        usage_field(usage_value, "cacheWriteInputTokens"),
    );

    let reasoning_text = collect_reasoning_text(content);
    let reasoning_encrypted_content = encode_reasoning_envelope(content);
    let reasoning_tokens = estimate_reasoning_tokens(&reasoning_text);

    let mut items: Vec<ResponseOutputItem> = Vec::new();

    // Spec order: a reasoning item FIRST, carrying the reasoning text in
    // `summary` (a structured item — NOT the chat path's `<think>` inline).
    if !reasoning_text.is_empty() || reasoning_encrypted_content.is_some() {
        items.push(ResponseOutputItem::Reasoning {
            id: format!("rs_{}", response_id.trim_start_matches("resp_")),
            content: None,
            summary: Some(json!([{ "type": "summary_text", "text": reasoning_text }])),
            encrypted_content: reasoning_encrypted_content,
        });
    }

    // Emit one function_call item per toolUse block whenever present,
    // DECOUPLED from stopReason (#8): a max_tokens / malformed_tool_use
    // truncation still surfaces whatever toolUse blocks landed. A message text
    // item is emitted when text exists (spec order: reasoning, message text,
    // then function_call items).
    let mut text = String::new();
    let mut tool_items: Vec<ResponseOutputItem> = Vec::new();
    for c in content {
        if let Some(part) = c.get("toolUse") {
            let call_id = part
                .get("toolUseId")
                .and_then(Value::as_str)
                .unwrap_or_default()
                .to_string();
            let name = part
                .get("name")
                .and_then(Value::as_str)
                .unwrap_or_default()
                .to_string();
            let input = part.get("input").cloned().unwrap_or(Value::Null);
            let arguments = serde_json::to_string(&input).map_err(|e| {
                AppError::Internal(format!("failed to serialize toolUse input: {e}"))
            })?;
            let status = tool_registry
                .resolve(&name)
                .filter(|binding| binding.kind != ResponsesToolKind::Function)
                .map(|_| "completed");
            tool_items.push(tool_output_item(
                tool_registry,
                &call_id,
                &name,
                &input,
                arguments,
                status,
            ));
        } else if let Some(t) = c.get("text").and_then(Value::as_str) {
            text.push_str(t);
        }
    }

    if !text.is_empty() {
        items.push(ResponseOutputItem::Message {
            id: format!("msg_{}", response_id.trim_start_matches("resp_")),
            status: "completed".to_string(),
            role: "assistant".to_string(),
            content: vec![OutputContentPart::OutputText {
                text,
                annotations: Vec::new(),
                logprobs: None,
            }],
        });
    } else if tool_items.is_empty() {
        // Neither text nor tool calls: keep the (empty) message item so the
        // output array is never empty (matches the prior non-tool_use branch).
        items.push(ResponseOutputItem::Message {
            id: format!("msg_{}", response_id.trim_start_matches("resp_")),
            status: "completed".to_string(),
            role: "assistant".to_string(),
            content: vec![OutputContentPart::OutputText {
                text: String::new(),
                annotations: Vec::new(),
                logprobs: None,
            }],
        });
    }
    items.extend(tool_items);

    let (status, incomplete_details) = map_status(stop_reason);

    let input_tokens_details = Some(InputTokensDetails {
        cached_tokens: counts.cached_tokens,
    });
    let output_tokens_details = Some(OutputTokensDetails {
        reasoning_tokens: reasoning_tokens as i32,
    });

    Ok(ResponsesResponse {
        id: response_id.to_string(),
        object: "response".to_string(),
        created_at: now_unix_secs(),
        status,
        output: items,
        usage: ResponsesUsage {
            input_tokens: counts.prompt_tokens,
            input_tokens_details,
            output_tokens: counts.completion_tokens,
            output_tokens_details,
            total_tokens: counts.total_tokens,
        },
        model: model.to_string(),
        instructions: req.instructions.clone(),
        temperature: req.temperature,
        top_p: req.top_p,
        tool_choice: req.tool_choice.clone(),
        tools: req.tools.clone(),
        max_output_tokens: req.max_output_tokens,
        parallel_tool_calls: req.parallel_tool_calls,
        error: None,
        incomplete_details,
    })
}

pub(crate) fn tool_output_item(
    registry: &ResponsesToolRegistry,
    call_id: &str,
    bedrock_name: &str,
    input: &Value,
    arguments: String,
    status: Option<&str>,
) -> ResponseOutputItem {
    let Some(binding) = registry.resolve(bedrock_name) else {
        return ResponseOutputItem::FunctionCall {
            id: Some(format!("fc_{call_id}")),
            call_id: call_id.to_string(),
            name: bedrock_name.to_string(),
            namespace: None,
            arguments,
            status: status.map(str::to_string),
        };
    };

    if binding.kind == ResponsesToolKind::Function {
        return ResponseOutputItem::FunctionCall {
            id: Some(format!("fc_{call_id}")),
            call_id: call_id.to_string(),
            name: binding.client_name.clone(),
            namespace: binding.namespace.clone(),
            arguments,
            status: status.map(str::to_string),
        };
    }

    let (item_type, id_prefix, payload_key, payload) = match binding.kind {
        ResponsesToolKind::Custom => (
            "custom_tool_call",
            "ct",
            "input",
            input
                .get("input")
                .cloned()
                .unwrap_or(Value::String(arguments)),
        ),
        ResponsesToolKind::LocalShell => (
            "local_shell_call",
            "lsc",
            "action",
            input
                .get("action")
                .cloned()
                .unwrap_or_else(|| input.clone()),
        ),
        ResponsesToolKind::Shell => ("shell_call", "sh", "action", input.clone()),
        ResponsesToolKind::ApplyPatch => (
            "apply_patch_call",
            "ap",
            "operation",
            input
                .get("operation")
                .cloned()
                .unwrap_or_else(|| input.clone()),
        ),
        ResponsesToolKind::Function => unreachable!(),
    };
    let mut fields = HashMap::new();
    fields.insert("id".to_string(), json!(format!("{id_prefix}_{call_id}")));
    fields.insert("call_id".to_string(), json!(call_id));
    fields.insert(payload_key.to_string(), payload);
    if binding.kind == ResponsesToolKind::Custom {
        fields.insert("name".to_string(), json!(binding.client_name));
    }
    if matches!(
        binding.kind,
        ResponsesToolKind::Shell | ResponsesToolKind::ApplyPatch
    ) {
        if let Some(status) = status {
            fields.insert("status".to_string(), json!(status));
        }
    }
    ResponseOutputItem::Other {
        item_type: item_type.to_string(),
        fields,
    }
}

/// Concatenate every `reasoningContent.reasoningText.text` across blocks.
fn collect_reasoning_text(content: &[Value]) -> String {
    let mut reasoning = String::new();
    for block in content {
        if let Some(t) = block
            .get("reasoningContent")
            .and_then(|rc| rc.get("reasoningText"))
            .and_then(|rt| rt.get("text"))
            .and_then(Value::as_str)
        {
            reasoning.push_str(t);
        }
    }
    reasoning
}

/// Map a Bedrock `stopReason` to a Responses `status` plus optional
/// `incomplete_details`.
///
/// `max_tokens` → `("incomplete", { "reason": "max_output_tokens" })`;
/// `content_filtered` → `("incomplete", { "reason": "content_filter" })`;
/// everything else → `("completed", None)`.
fn map_status(stop_reason: Option<&str>) -> (String, Option<Value>) {
    match stop_reason.map(str::to_lowercase).as_deref() {
        Some("max_tokens") => (
            "incomplete".to_string(),
            Some(json!({ "reason": "max_output_tokens" })),
        ),
        Some("content_filtered") => (
            "incomplete".to_string(),
            Some(json!({ "reason": "content_filter" })),
        ),
        _ => ("completed".to_string(), None),
    }
}

/// Read an integer usage field, defaulting to 0 (matches the chat mapper).
fn usage_field(usage: Option<&Value>, key: &str) -> i32 {
    usage
        .and_then(|u| u.get(key))
        .and_then(Value::as_i64)
        .unwrap_or(0) as i32
}

/// Current Unix time in whole seconds.
fn now_unix_secs() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

#[cfg(test)]
#[path = "responses_response_tests.rs"]
mod tests;
